### ISSUE TITLE
MVPリリースレビュー依頼

### ISSUE THREAD

**Issue by akanesi05** [akanesi05/peace#42]
## 各種情報
サービス名 
ピス卒
サービスURL
https://peace-4ap7.onrender.com/poses

## READMEレビュー時にMVPリリース時点で実装予定だった機能

- [x] 会員登録
- [x] ログイン
- [x] マイページ
- [x] ポーズの投稿されたポーズの一覧機能
- [x] ポーズ投稿機能（画像とポーズ名を入れる。）、編集、削除
- [x] ブックマーク機能
- [x] ポーズ検索機能（オートコンプリート検索、例: 'ピース'を検索する際に'ピ'と入力すると保管してくれるものを想定してます）
- [x] パスワードリセット機能

READMEレビュー時に実装予定だった機能が実装できているかがわかるように記載してください

## サービスイメージがわかるようなスクリーンショット等
[![Image from Gyazo](https://i.gyazo.com/49258a6d627c14bb20267667cec28f75.png)](https://gyazo.com/49258a6d627c14bb20267667cec28f75)
[![Image from Gyazo](https://i.gyazo.com/ba818b70a5a32b4b5e0e3fa762239c62.jpg)](https://gyazo.com/ba818b70a5a32b4b5e0e3fa762239c62)

[![Image from Gyazo](https://i.gyazo.com/370027f961e9aba5b665df2cffbe1dee.png)](https://gyazo.com/370027f961e9aba5b665df2cffbe1dee)

**Comment by tmtkzk0823** [comment]
READMEに記載されている内容が実装できていると思います！
LGTMです！
